// The real VIBE Performance System — four matte-black tins, each with a
// glowing LED-style ring. `glow` drives the emissive ring, accent light,
// bloom halo, and the page's accent. Data from the product spec.
export const PRODUCTS = [
  {
    id: "pro",
    shopifyVariant: "53287109394765",
    name: "PRO",
    positioning: "Intensity",
    glow: "#ff2e3a",
    glowDeep: "#7a0d14",
    tagline: "Maximum drive, zero compromise.",
    blurb:
      "Our highest-payload pouch — a serious stimulant stack for heavy training and peak output. Built for the moments that demand everything.",
    stimulant: "75mg",
    stimulantLabel: "caffeine",
    payload: "Very high",
    wear: "20–30 min",
    price: "£19.99",
    actives: [
      { dose: "75mg", name: "Caffeine" },
      { dose: "100mg", name: "Methylliberine (Dynamine®)" },
      { dose: "100mg", name: "Alpha-GPC" },
      { dose: "150mg", name: "L-Tyrosine" },
    ],
  },
  {
    id: "endure",
    shopifyVariant: "53287109329229",
    name: "ENDURE",
    positioning: "Endurance",
    glow: "#27e06a",
    glowDeep: "#0c6e30",
    tagline: "Go longer. Stay smooth.",
    blurb:
      "A micro-dosed, electrolyte-rich pouch with adaptogens for the long efforts. Steady energy that lasts — without the spike.",
    stimulant: "30mg",
    stimulantLabel: "caffeine",
    payload: "High",
    wear: "20–30 min",
    price: "£19.99",
    actives: [
      { dose: "30mg", name: "Caffeine (micro-dose)" },
      { dose: "300mg", name: "Rhodiola rosea" },
      { dose: "500mg", name: "Taurine" },
      { dose: "25mg", name: "Magnesium (glycinate)" },
    ],
  },
  {
    id: "focus",
    shopifyVariant: "53287108706637",
    name: "FOCUS",
    positioning: "Deep Work",
    glow: "#36a6ff",
    glowDeep: "#0b3f7a",
    tagline: "Clean, sharp, sustained attention.",
    blurb:
      "Paraxanthine-driven clarity with nootropics for deep work. Alert focus and flow, none of the caffeine jitter.",
    stimulant: "100mg",
    stimulantLabel: "paraxanthine",
    payload: "Medium",
    wear: "20–30 min",
    price: "£19.99",
    actives: [
      { dose: "100mg", name: "Paraxanthine (enfinity®)" },
      { dose: "200mg", name: "L-Theanine" },
      { dose: "75mg", name: "Alpha-GPC" },
      { dose: "200mg", name: "Rhodiola rosea" },
    ],
  },
  {
    id: "calm",
    shopifyVariant: "53287108641101",
    name: "CALM",
    positioning: "Recovery",
    glow: "#a557ff",
    glowDeep: "#4a1a8a",
    tagline: "Wind down. Reset.",
    blurb:
      "A caffeine-free recovery pouch with calming adaptogens for after the session and before sleep. Softness and long-wear comfort.",
    stimulant: "0mg",
    stimulantLabel: "caffeine-free",
    payload: "Medium",
    wear: "20–30 min",
    price: "£19.99",
    actives: [
      { dose: "300mg", name: "Ashwagandha (KSM-66®)" },
      { dose: "200mg", name: "L-Theanine" },
      { dose: "500mg", name: "Glycine" },
      { dose: "100mg", name: "Magnesium (glycinate)" },
    ],
  },
];
